AgendaTelefonica.MVC/Controllers/ContatoController.cs
using AgendaTelefonica.ApplicationService.Contracts;
using AgendaTelefonica.Domain.Entities;
using AgendaTelefonica.Domain.Entities.Enums;
using AgendaTelefonica.Domain.Validation;
using AgendaTelefonica.MVC.AutoMapper;
using AgendaTelefonica.MVC.Helpers;
using AgendaTelefonica.MVC.Helpers.UTIL;
using AgendaTelefonica.MVC.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace AgendaTelefonica.MVC.Controllers
{
	public class ContatoController : Controller
	{
		readonly IAppServiceNotification _appServiceNotification;
		readonly IAppServiceContato _appServiceContato;

		public ContatoController(IAppServiceNotification appServiceNotification, IAppServiceContato appServiceContato)
		{
			_appServiceNotification = appServiceNotification;
			_appServiceContato = appServiceContato;
		}

		public ActionResult Index()
		{
			return View();
		}

		public JsonResult Listar(DTParameters param)
		{
			string[] columnFilters = param.Columns.Select(x => x.Search.Value).ToArray();

			string criterio = null;
			if (!string.IsNullOrEmpty(columnFilters[0]))
				criterio = columnFilters[0].ToLower();

			IEnumerable<Contato> contatos = String.IsNullOrEmpty(criterio) ? _appServiceContato.All() :
				_appServiceContato.Find(w => w.Nome.Contains(criterio)
			   || w.Telefone.Any(wt => wt.Numero.Contains(criterio) || wt.Numero.Contains(criterio))
			   || w.Email.Any(we => we.Endereco.Contains(criterio)));

			List<object> dados = contatos.Select(s => FormatDataView(s)).ToList();

			DTResult<object> result = new DTResult<object>
			{
				draw = param.Draw,
				data = dados,
				recordsFiltered = param.TotalRegistros,
				recordsTotal = param.TotalRegistros
			};

			return Json(result, JsonRequestBehavior.AllowGet);
		}

		public ActionResult Edit(int? id)
		{
			ObterBase();
			ContatoViewModel model = null;

			try
			{

				if (id == null)
					model = new ContatoViewModel();
				else
				{
					var contato = _appServiceContato.Get(id.GetValueOrDefault());
					model = MapperConfig.Mapper.Map<ContatoViewModel>(contato);
				}
			}
			catch (Exception ex)
			{
				ObterBase();
				int codigoNotificacao = _appServiceNotification.Notify(ex.Message);
				TempData["AlertaFeedback"] = AlertaFeedback.CriaAlerta($"Ocorreu ao salvar o contato. CÓDIGO DE ERRO: {codigoNotificacao}", EnumTipoAlertaFeedback.Erro);
			}
			return View(model);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit(ContatoViewModel model)
		{
			try
			{
				if (ModelState.IsValid)
				{
					model.Telefone.RemoveAll(w => w.Excluir);
					model.Email.RemoveAll(w => w.Excluir);
					Contato contato = MapperConfig.Mapper.Map<ContatoViewModel, Contato>(model);

					var validation = _appServiceContato.SaveOrUpdate(contato);
					if (GetFeedback(validation))
						return RedirectToAction("Index");
				}
			}
			catch (Exception ex)
			{
				ObterBase();
				int codigoNotificacao = _appServiceNotification.Notify(ex.Message);
				TempData["AlertaFeedback"] = AlertaFeedback.CriaAlerta($"Ocorreu ao salvar o contato. CÓDIGO DE ERRO: {codigoNotificacao}", EnumTipoAlertaFeedback.Erro);
			}
			return View(model);
		}

		private bool GetFeedback(ValidationResult validation)
		{
			string mensagem = "Contato salvo com sucesso!";
			EnumTipoAlertaFeedback feedback = EnumTipoAlertaFeedback.Sucesso;
			if (!validation.IsValid)
			{
				mensagem = String.Join("-", validation.Errors.Select(s => s.Message));
				feedback = EnumTipoAlertaFeedback.Atencao;
			}
			TempData["AlertaFeedback"] = AlertaFeedback.CriaAlerta(mensagem, feedback);

			return feedback == EnumTipoAlertaFeedback.Sucesso;
		}

		// GET: Aplicacao/Delete/5
		public ActionResult Delete(int id)
		{
			try
			{
				var contato = _appServiceContato.Get(id);

				var validation = _appServiceContato.Delete(contato);
				GetFeedback(validation);
			}
			catch (Exception ex)
			{
				int codigoNotificacao = _appServiceNotification.Notify(ex.Message);
				TempData["AlertaFeedback"] = AlertaFeedback.CriaAlerta($"Ocorreu ao excluir o contato. CÓDIGO DE ERRO: {codigoNotificacao}", EnumTipoAlertaFeedback.Erro);
			}
			return RedirectToAction("Index");
		}

		void ObterBase()
		{
			ViewBag.Classificacao = new SelectList(new[]
			{
				new {value = (int)EnumClassificacao.Casa,text="Casa" },
				new {value = (int)EnumClassificacao.Outro,text="Outro" },
				new {value =(int) EnumClassificacao.Trabalho,text="Trabalho" },
			}, "value", "text");
		}
		object FormatDataView(Contato s)
		{
			return new
			{
				s.Id,
				s.Nome,
				Telefone = String.Join("/", s.Telefone.Select(st => $"{st.DDD} - {st.Numero} { (EnumClassificacao)st.Classificacao}")),
				Email = String.Join("/", s.Email.Select(se => $"{se.Endereco} { (EnumClassificacao)se.Classificacao}"))
			};
		}
	}
}

AgendaTelefonica.MVC/Controllers/HomeController.cs
using System.Web.Mvc;

namespace AgendaTelefonica.MVC.Controllers
{
	public class HomeController : Controller
	{
		public ActionResult Index()
		{
			return View();
		}

	}
}

AgendaTelefonica.MVC/Views/Contato/Edit.cshtml
@using AgendaTelefonica.MVC.Helpers
@model AgendaTelefonica.MVC.ViewModel.ContatoViewModel

@{
    ViewBag.Title = "Edit";
}

@section scriptCss{
    <link href="@Url.Content("~/Content/css/iCheck/minimal/_all.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/css/select2/select2.min.css")" rel="stylesheet" />
}
@using (Html.BeginForm("Edit", "Contato", FormMethod.Post, new { @class = "form-horizontal", enctype = "multipart/form-data", role = "form" }))
{
    @Html.AntiForgeryToken()


    <section class="content-header">
        <h1>
            Contato
            @{
                if (Model.Id == 0)
                {
                    <small>Cadastrar</small>
                }
                else
                {
                    <small>Editar</small>
                }
            }

        </h1>
    </section>
    <section class="content">
        <div class="row">

        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="box-body">

                    <div class="nav-tabs-custom">
                        <ul class="nav nav-tabs">
                            <li class="active"><a href="#tab_princ_1" data-toggle="tab">Informações Básicas</a></li>
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane active" id="tab_princ_1">
                                <fieldset>
                                    <legend style="margin-bottom: 2px;">Cabeçalho</legend>

                                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                    @*@Html.HiddenFor(model => model.Id)*@
                                    <div class="row">
                                        <div class="col-md-2">
                                            @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label" })

                                            @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
                                        </div>
                                        <div class="col-md-3">
                                            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label" })

                                            @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control", maxlength = "60" } })
                                            @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                                        </div>
                                        <div class="col-md-3">
                                            @Html.LabelFor(model => model.Empresa, htmlAttributes: new { @class = "control-label" })

                                            @Html.EditorFor(model => model.Empresa, new { htmlAttributes = new { @class = "form-control", maxlength = "50" } })
                                            @Html.ValidationMessageFor(model => model.Empresa, "", new { @class = "text-danger" })
                                        </div>
                                        <div class="col-md-3">
                                            @Html.LabelFor(model => model.Endereco, htmlAttributes: new { @class = "control-label" })

                                            @Html.EditorFor(model => model.Endereco, new { htmlAttributes = new { @class = "form-control", maxlength = "150" } })
                                            @Html.ValidationMessageFor(model => model.Endereco, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </fieldset>
                                <br />

                                <fieldset>
                                    <legend style="margin-bottom: 2px;">Telefone</legend>

                                    <div id="ContatoTelefoneContainer">
                                        @Html.EditorFor(model => model.Telefone)
                                    </div>
                                    <br />
                                    <div class="col-md-4 linkAddTelefone">
                                        @Html.LinkToAddNestedForm("Adicionar Telefone", "#ContatoTelefoneContainer", ".linhaTelefone", "Telefone", typeof(AgendaTelefonica.MVC.ViewModel.ContatoTelefoneViewModel), true, false, false, false)
                                    </div>

                                    <hr />
                                </fieldset>


                                <fieldset>
                                    <legend style="margin-bottom: 2px;">E-mail</legend>

                                    <div id="ContatoEmailContainer">
                                        @Html.EditorFor(model => model.Email)
                                    </div>
                                    <br />
                                    <div class="col-md-4 linkAddEmail">
                                        @Html.LinkToAddNestedForm("Adicionar Email", "#ContatoEmailContainer", ".linhaEmail", "Email", typeof(AgendaTelefonica.MVC.ViewModel.ContatoEmailViewModel), true, false, false, false)
                                    </div>

                                    <hr />
                                </fieldset>
                            </div>

                        </div>
                    </div>

                </div>
            </div>
        </div>

        <div class="footer">
            <div class="row">
                <div class="col-md-2">
                    <a href="~/Contato" class="btn btn-danger form-control" style="vertical-align: middle;" title="Novo"><i class="fa fa-fw fa-add"></i>Cancelar</a>
                </div>
                <div class="col-md-2">
                    <input type="submit" value="Salvar" class="btn btn-success form-control" />
                </div>
            </div>
        </div>
    </section>
}
@section scriptJs{
    <script src="@Url.Content("~/scripts/plugins/select2/select2.js")"></script>
    <script src="@Url.Content("~/scripts/plugins/select2/i18n/pt-BR.js")"></script>
    <script>
        $(".select2").each(function (index, value) {
            var placeh = $(this).attr("placeholder");
            $(this).select2({
                placeholder: placeh,
                allowClear: true,
                language: "pt-BR"
            });
        });

    </script>
}

AgendaTelefonica.MVC/Views/Contato/EditorTemplates/ContatoEmailViewModel.cshtml
@using AgendaTelefonica.MVC.Helpers
@model AgendaTelefonica.MVC.ViewModel.ContatoEmailViewModel



<div class="row linhaDivisao" style="@(Model.Excluir == true ? "display: none;" : "") ">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.ContatoId)

    <div class="col-md-6">
        @Html.Label("Endereço (E-mail)", htmlAttributes: new { @class = "control-label" })

        @Html.EditorFor(model => model.Endereco, new { htmlAttributes = new { @class = "form-control", maxlength = "100" } })
        @Html.ValidationMessageFor(model => model.Endereco, "", new { @class = "text-danger" })
    </div>

    <div class="col-md-4">
        @Html.Label("Classificação", htmlAttributes: new { @class = "control-label" })

        @Html.DropDownListFor(x => x.Classificacao, new SelectList(Enum.GetValues(typeof(AgendaTelefonica.Domain.Entities.Enums.EnumClassificacao))), "", new { @class = "select2 form-control ", @style = "width: 100%;", @placeholder = "Selecione" })
        @Html.ValidationMessageFor(model => model.Classificacao, "", new { @class = "text-danger" })
    </div>

    <div class="col-md-1 colRemoveLista" style="margin-top: 24px;" idRegistroListaPai="@Model.Id">
        @Html.LinkToRemoveNestedForm("Remover", "div.linhaEmail", "input.mark-for-delete")
        @Html.HiddenFor(model => model.Excluir, new { @class = "mark-for-delete" })
    </div>
</div>

AgendaTelefonica.MVC/Views/Contato/EditorTemplates/ContatoTelefoneViewModel.cshtml
@using AgendaTelefonica.MVC.Helpers
@model AgendaTelefonica.MVC.ViewModel.ContatoTelefoneViewModel



<div class="row linhaDivisao" style="@(Model.Excluir == true ? "display: none;" : "") ">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.ContatoId)


    <div class="col-md-3">
        @Html.LabelFor(model => model.DDD, htmlAttributes: new { @class = "control-label" })

        @Html.EditorFor(model => model.DDD, new { htmlAttributes = new { @class = "form-control", maxlength = "4" } })
        @Html.ValidationMessageFor(model => model.DDD, "", new { @class = "text-danger" })
    </div>
    <div class="col-md-4">
        @Html.LabelFor(model => model.Numero, htmlAttributes: new { @class = "control-label" })

        @Html.EditorFor(model => model.Numero, new { htmlAttributes = new { @class = "form-control", maxlength = "9" } })
        @Html.ValidationMessageFor(model => model.Numero, "", new { @class = "text-danger" })
    </div>

    <div class="col-md-4">
        @Html.Label("Classificação", htmlAttributes: new { @class = "control-label" })

        @Html.DropDownListFor(x => x.Classificacao, new SelectList(Enum.GetValues(typeof(AgendaTelefonica.Domain.Entities.Enums.EnumClassificacao))), "", new { @class = "select2 form-control ", @style = "width: 100%;", @placeholder = "Selecione" })
        @Html.ValidationMessageFor(model => model.Classificacao, "", new { @class = "text-danger" })
    </div>

    <div class="col-md-1 colRemoveLista" style="margin-top: 24px;" idRegistroListaPai="@Model.Id">
        @Html.LinkToRemoveNestedForm("Remover", "div.linhaTelefone", "input.mark-for-delete")
        @Html.HiddenFor(model => model.Excluir, new { @class = "mark-for-delete" })
    </div>
</div>

AgendaTelefonica.MVC/Views/Contato/Index.cshtml
@using AgendaTelefonica.MVC.Helpers
@{
    ViewBag.Title = "Index";
}
@section scriptCss
{
    <link href="@Url.Content("~/Content/css/dataTables/dataTables.bootstrap.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/css/dataTables/dataTables.tableTools.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/css/select2/select2.min.css")" rel="stylesheet" />
}

<!--GRID-->
<div class="row">
    <div class="col-md-12">
        <div class="box box-default no-margin">
            <div class="box-header with-border">
                <div class="row">
                    <div class="col-md-10">
                        <h3 class="box-title"><i class="fa fa-fw fa-table"></i>Resultado</h3>
                    </div>

                    <div class="col-md-2">
                        <a href="~/Contato/Edit" class="btn btn-success form-control" style="vertical-align: middle;" title="Novo"><i class="fa fa-fw fa-add"></i>Novo</a>
                    </div>
                </div>
                <div class="row">

                    <div class="col-md-3">
                        @Html.Label("Nome:")
                        @Html.TextBox("Nome", "", new { @class = "form-control ", @indiceTabela = 0, @idTabela = "tblContato", @style = "width: 100%;" })
                    </div>
                    <div class="col-md-2">
                        <label>&nbsp;</label>
                        <button type="button" class="btn btn-primary form-control btnFiltrar" style="vertical-align: middle;" title="Pesquisar" idTabela="tblContato"><i class="fa fa-fw fa-search"></i>Pesquisar</button>
                    </div>
                    <div class="col-md-2">
                        <label>&nbsp;</label>
                        <button type="button" class="btn btn-primary form-control btnLimpar" style="vertical-align: middle;" title="Limpar"><i class="fa fa-fw fa-trash-o"></i>Limpar</button>
                    </div>
                </div>

            </div>
            <div class="box-body">
                <table id="tblContato" class="table table-bordered table-hover">
                    <thead class="thead-inverse">
                        <tr>
                            <th>Ação</th>
                            <th>Nome</th>
                            <th>Telefone</th>
                            <th>E-mail</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
                @Html.Label(" ", new { @class = "help-block", @id = "MsgValidacao" })
            </div>
        </div>
    </div>

</div>

@{
    string url = "~/Contato/Listar";

}

@section scriptJs{


    <script type="text/javascript" src="@Url.Content("~/scripts/plugins/dataTables/jquery.dataTables.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/scripts/plugins/dataTables/dataTables.bootstrap.min.js")"></script>
    <script src="@Url.Content("~/scripts/plugins/dataTables/dataTables.tableTools.js")"></script>
    <script src="@Url.Content("~/scripts/plugins/dataTables/ZeroClipboard.js")"></script>
    <script src="@Url.Content("~/scripts/plugins/dataTables/TableTools.js")"></script>
    <script src="@Url.Content("~/scripts/plugins/dataTables/customFilters.js")"></script>
    <script src="@Url.Content("~/scripts/plugins/select2/select2.js")"></script>
    <script src="@Url.Content("~/scripts/plugins/select2/i18n/pt-BR.js")"></script>
    <script>
        $(".select2").each(function (index, value) {
            var placeh = $(this).attr("placeholder");
            $(this).select2({
                placeholder: placeh,
                allowClear: true,
                language: "pt-BR"
            });
        });
        var oTable = null;
        $(function() {

            oTable = $('#tblContato').DataTable({
                "serverSide": true,
                "ajax": {
                    "type": "POST",
                    "url": '@Url.Content(url)',
                    "contentType": 'application/json; charset=utf-8',
                    'data': function(data) { return data = JSON.stringify(data);
                    },
                },
                "scrollX": true,
                "processing": true,
                "paging": true,
                "pageLength": 30,
                "lengthChange": false,
                "searching": true,
                "ordering": true,
                "info": true,
                "autoWidth": true,
                "deferRender": false,
                "language":
                {
                    "url": "@Url.Content("~/scripts/plugins/dataTables/languagePT-BR.json")"
                },
                "columns": [
           {
               "data": "Id",
               "render": function(data) {
                   var links = "";
                    @{
                    <text>
                  links =  "<a href='@Url.Action("edit", "Contato")?id=" + data + "' title='Editar' class='btn btn-xs btn-warning'><span class='fa fa-edit'></span></a>";
                     links += "<a onclick='return confirm(\"Deseja excluir esse registro?\");' href='@Url.Action("delete", "contato")?id=" + data + "' title='Excluir' class='btn btn-xs btn-danger'><span class='fa fa-ban'></span></a>";
                   </text>
                        }
                   return links;
               }
           },
           { "data": "Nome" },
           { "data": "Telefone" },
           { "data": "Email" },
                ],
                "order": [1, "asc"],
                dom: 'T<"clear">lfrtip',
                tableTools: {
                    "sSwfPath": '',
                   "aButtons": []
                },
            });


        });
    </script>

}

AgendaTelefonica.MVC/Views/Home/Index.cshtml
@{
    
}


<h2>Home Index</h2>

AgendaTelefonica.MVC/Views/Shared/PartialViews/_AlertaFeedback.cshtml
@using AgendaTelefonica.MVC.Helpers
@{ 
    if (TempData["AlertaFeedback"] != null)
    {
        AlertaFeedback alertaFeedback = TempData["AlertaFeedback"] as AlertaFeedback;

        string classDiv = string.Empty;
        string classIcon = string.Empty;


        switch (alertaFeedback.TipoAlertaFeedback)
        {
            case EnumTipoAlertaFeedback.Sucesso:
                classDiv = "alert-success";
                classIcon = "fa-check";

                break;
            case EnumTipoAlertaFeedback.Erro:
                classDiv = "alert-danger";
                classIcon = "fa-ban";

                break;
            case EnumTipoAlertaFeedback.Atencao:
                classDiv = "alert-warning";
                classIcon = "fa-exclamation-circle";

                break;
            default:
                break;
        }
        <div class="box-body alert" style="padding-bottom: 0px; margin-bottom: 5px; max-height: 160px; overflow-y: auto; word-wrap: break-word;" id="AlertaFeddBack">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true" style="margin-right:3px;">&times;</button>
            <div class="alert @classDiv alert-dismissible" style="margin-bottom: 5px;">
                <h4><i class="icon fa @classIcon"></i> @alertaFeedback.Titulo</h4>
                <div style="white-space:pre-line;">@{ if (!String.IsNullOrEmpty(alertaFeedback.CodigoExcecao))
                    {<b>Código: </b>@alertaFeedback.CodigoExcecao<br />}}@alertaFeedback.Mensagem.Trim()</div>
                </div>
                <hr style="margin-top: 0px; margin-bottom: 0px;border-color:#d2d6de;" />
            </div>
                    }
}

AgendaTelefonica.MVC/Views/Shared/PartialViews/_Menu.cshtml
@using AgendaTelefonica.MVC.ViewsModels.Comum
@using System.Collections.Generic;

@{
    List<MenuVM> menu = new MenuVM().ObterMenu();

    string nomeController = HttpContext.Current.Request.RequestContext.RouteData.Values["controller"].ToString();
}
<aside class="main-sidebar">
    <section class="sidebar">
        <div class="user-panel">
            <div class="pull-left image">
                <img src="~/Content/img/user.png" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>@(Request.IsAuthenticated ? HttpContext.Current.User.Identity.Name : "Usuário Logado")</p>
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>

        @{
            if (menu != null && menu.Count > 0)
            {
                <ul class="sidebar-menu">
                    <li class="header">MENU</li>

                    @foreach (MenuVM itemMenu in menu)
                    {
                        <li class="treeview @(itemMenu.Ativo.Contains(nomeController) ? "active" : "" )">
                            <a href="#">
                                <i class="@itemMenu.Icone"></i> <span>@itemMenu.Descricao</span> <i class="fa fa-angle-left pull-right"></i>
                            </a>
                            <ul class="treeview-menu">
                                @foreach (MenuVM itemSubItem in itemMenu.SubItens)
                                {
                                    if (itemSubItem.SubItens == null || itemSubItem.SubItens.Count() == 0)
                                    {
                                        <li class="@(itemSubItem.Ativo.Contains(nomeController) ? "active" : "" )">
                                            <a href="@Url.Content(itemSubItem.Url)" style="white-space: normal;"><i class="@itemSubItem.Icone"></i> @itemSubItem.Descricao</a>
                                        </li>
                                    }
                                    else
                                    {
                                        <li class="@(itemSubItem.Ativo.Contains(nomeController) ? "active" : "" )">
                                            <a href="#" style="white-space: normal;"><i class="fa @itemSubItem.Icone"></i> @itemSubItem.Descricao <i class="fa fa-angle-left pull-right"></i></a>
                                            <ul class="treeview-menu">
                                                @{ foreach (MenuVM itemSubItemItem in itemSubItem.SubItens)
                                                    {
                                                        <li class="@(itemSubItemItem.Ativo.Contains(nomeController) ? "active" : "" )">
                                                            <a href="@Url.Content(itemSubItemItem.Url)" style="white-space: normal;"><i class="fa fa-circle-o"></i> @itemSubItemItem.Descricao</a>
                                                        </li>
                                                    }
                                                }
                                            </ul>
                                        </li>
                                    }
                                }
                            </ul>
                        </li>
                    }

                </ul>
            }
        }
    </section>
</aside>

AgendaTelefonica.MVC/Views/Shared/_Layout.cshtml
@using AgendaTelefonica.MVC.Helpers;
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Agenda telefonica</title>

    <link href="@Url.Content("~/Content/css/bootstrap/bootstrap.css")" rel="stylesheet" />
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">

    @RenderSection("scriptCss", required: false)
    @Html.PartialRenderScripts(EnumTipoScript.Css)

    <link href="@Url.Content("~/Content/css/dist/AdminLTE.min.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/css/dist/skins/_all-skins.min.css")" rel="stylesheet" />
    
</head>
<body class="hold-transition skin-yellow sidebar-mini wysihtml5-supported">

    <div class="wrapper">

        <header class="main-header">
            <a href="@Url.Content("~/Home")" class="logo">
                <span class="logo-mini"><b>MVC</b></span>
                <span class="logo-lg"><b>Template MVC</b></span>
            </a>
            <nav class="navbar navbar-static-top">
                <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        
                    </ul>
                </div>
            </nav>
        </header>

        @Html.Partial("PartialViews/_Menu")
        

        <div class="content-wrapper" style="min-height: 946px;">
            @Html.Partial("PartialViews/_AlertaFeedback")
            @RenderBody()
        </div>

        <footer class="main-footer">
            <div class="pull-right hidden-xs">
                <b>Versão</b> 1.0.0
            </div>
            <strong>Copyright &copy; 2017 <a href="http://www.tegma.com.br">AgendaTelefonica.MVC Gestão Logistica</a>.</strong> Todos os direitos reservados.
        </footer>

        <script src="@Url.Content("~/scripts/plugins/jQuery/jQuery-2.2.0.min.js")"></script>

        <script src="http://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
        <script>
            $.widget.bridge('uibutton', $.ui.button);
        </script>
        <script src="@Url.Content("~/scripts/bootstrap/bootstrap.min.js")"></script>
        <script src="@Url.Content("~/scripts/dist/app.min.js")"></script>
        <script src="@Url.Content("~/scripts/main.js")"></script>
        <script src="@Url.Content("~/scripts/plugins/jQuery/SmartNotification.js")"></script>
        <script type="text/javascript">
            
        </script>

        @RenderSection("scriptJs", required: false)
        @Html.PartialRenderScripts(EnumTipoScript.Javascript)
        </div>
</body>
</html>